### ISSUE TITLE
Create training YAML data file using some training schema and populate with data

### ISSUE THREAD

**Issue by anenadic** [EVERSE-ResearchSoftware/RSQKit#127]
Decide on a simple schema (use BioSchemas as superset) and add a few training resources that can be used to tag pages.

An example schema that may be sufficient for our needs may look like:

```yaml
- description: A tutorial on software quality
  id: scikit-learn
  name: scikit-learn
  url: https://scikit-learn.org
  domain: [life sciences, biohealth]
  quality_indicator: [] # which quality indicators, if any, this training resource addresses 
```

Decide how to handle links to TeSS, if this training is included there - e.g. do we have an extra field `tess_url`.

The next step is to curate the task pages with training and add support for this, similar it exists for tools with the {% tool "tool name" %} directive from the elixir theme plugin.
