### ISSUE TITLE
Adding FORTRAN to tools/service

### ISSUE THREAD

**Issue by ebreitmo** [EVERSE-ResearchSoftware/RSQKit#262]
Add FORTRAN to https://everse.software/RSQKit/all_tools_and_resources

**Comment by stafusa** [comment]
I believe it should be added to `_data/tool_and_resource_list.yml`.

A suggestion for the entry:

```yaml
- description: Fortran is a high-performance parallel programming language. It allows imperative, procedural, array-oriented, object-oriented, and functional paradigms. Fortran is a relatively small language that has been designed from the ground up for computationally intensive applications in science and engineering.
  id: fortran
  name: Fortran
  url: https://fortran-lang.org/
```
