### ISSUE TITLE
Investigate adding ‘Source’ field to Tools and Resources file for tagging origins (e.g., TechRadar/RSQkit)

### ISSUE THREAD

**Issue by shraddha-bajare** [EVERSE-ResearchSoftware/RSQKit#395]
We need to determine whether it's feasible to add a new source field to the tools and resources file without causing any issues or breaking existing functionality. This field would allow us to tag the origin of specific entries (e.g., TechRadar/RSQkit).

Tasks:

- Test adding a source field to ensure compatibility and stability
- Confirm that existing tools continue to function as expected with the new field

If successful, this addition will help track the provenance of entries and improve content traceability.

**Comment by shraddha-bajare** [comment]
agree, on the source as url of the tool
here, I believe  we will consider source field for tagging the tools from list
e.g 

```
- description: "Docker is a tool for creating isolated environments (application isolation) for software development called containers to enable consistent software running across platforms. 
  Docker allows developers to build, share, run and verify applications easily. DockerHub is a repository for sharing and managing container images."
  id: docker
  name: Docker
  registry:
  url: https://www.docker.com/
  source: TechRadar
```

```
- description: Julia is a high-performance programming language designed for numerical and scientific computing that combines the speed of C with the ease of use of Python. It features multiple dispatch, optional typing, and excellent parallel processing capabilities, making it particularly strong for mathematical computations, data science, and machine learning applications.
  id: julia
  name: Julia
  url: https://julialang.org/
  source: RSQKit
```
We can extend the source as TechRadar/RSQKit to include tool reference link on TechRadar/RSQKit
